# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.28.154114'

RELEASE_GIT_HEAD = '1dea12be82fe878c9533741a151d165da12f352d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'kissph2025-sys/yt-dlp_amirahtv'

ORIGIN = 'kissph2025-sys/yt-dlp_amirahtv'

_pkg_version = '2025.12.28.154114'
