# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.28.133737'

RELEASE_GIT_HEAD = '89ba323b0ce6041b56e6e274137307de74928180'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'kissph2025-sys/yt-dlp_amirahtv'

ORIGIN = 'kissph2025-sys/yt-dlp_amirahtv'

_pkg_version = '2025.12.28.133737'
